packages:
  - name: quiet-news
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    functions:
      - name: current-edition
        main: main
        runtime: nodejs:24
        web: true
        annotations:
          web-custom-options: true
        limits:
          timeout: 5000
          memory: 256
          logs: 8
